/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React from 'react';
import {
    BrushIcon, PhotoIcon, LayersIcon, SparkleIcon,
    FaceSmileIcon, VideoCameraIcon,
    AdjustmentsHorizontalIcon, CropIcon, PaletteIcon,
    ScissorsIcon, ArrowUpOnSquareIcon, TextToolIcon, LightbulbIcon,
    MagicWandIcon, LowPolyIcon, UserIcon, FilmGrainIcon, UnblurIcon,
    PatternIcon, TextEffectsIcon, VectorIcon, LogoIcon, StickersIcon, CaricatureIcon, Model3DIcon,
    BananaIcon,
    EraserIcon,
    CameraIcon,
    PolaroidWithArtistIcon, 
    TextureIcon,
    HomeIcon,
    BuildingIcon,
    CombineIcon,
    ExpandIcon,
    SwapIcon,
    LineArtIcon,
    FaceSparkleIcon,
    BoltIcon,
    FireIcon,
    PixelsIcon,
    ToyIcon,
    SharpenIcon,
    PngIcon,
    ShieldCheckIcon,
    DoubleExposureIcon,
    SuperheroIcon,
    SuperHeroFusionIcon,
    StyledPortraitIcon,
    WardrobeIcon, 
    SuperheroPoseIcon,
} from '../components/icons';
import { type ToolId, type ToolConfig, type TabId } from '../types';

export const tools: ToolConfig[] = [
    // Ferramentas de Geração (isEditingTool: false)
    { id: 'imageGen', name: 'Gerador de Imagens AI', description: 'Crie imagens a partir de descrições de texto.', icon: React.createElement(PhotoIcon, { className: 'w-8 h-8 text-purple-400' }), category: 'generation', isEditingTool: false },
    { id: 'sketchRender', name: 'Renderização de Esboço', description: 'Transforme seus desenhos em imagens realistas.', icon: React.createElement(BrushIcon), category: 'generation', isEditingTool: false },
    { id: 'characterDesign', name: 'Design de Personagem', description: 'Desenvolva conceitos de personagens únicos.', icon: React.createElement(FaceSmileIcon), category: 'generation', isEditingTool: false },
    { id: 'videoGen', name: 'Gerador de Vídeo AI', description: 'Crie vídeos curtos a partir de texto.', icon: React.createElement(VideoCameraIcon), category: 'generation', isEditingTool: false },
    { id: 'patternGen', name: 'Gerador de Padrões', description: 'Crie padrões de fundo sem costura.', icon: React.createElement(PatternIcon), category: 'generation', isEditingTool: false },
    { id: 'textEffects', name: 'Efeitos de Texto', description: 'Aplique efeitos visuais a um texto.', icon: React.createElement(TextEffectsIcon), category: 'generation', isEditingTool: false },
    { id: 'logoGen', name: 'Gerador de Logotipo AI', description: 'Crie logotipos únicos a partir de um conceito.', icon: React.createElement(LogoIcon), category: 'generation', isEditingTool: false },
    { id: 'stickerCreator', name: 'Criador de Adesivos AI', description: 'Gere adesivos a partir de um prompt.', icon: React.createElement(StickersIcon), category: 'generation', isEditingTool: false },
    { id: 'model3DGen', name: 'Gerador de Modelo 3D', description: 'Crie renderizações de objetos 3D.', icon: React.createElement(Model3DIcon), category: 'generation', isEditingTool: false },
    
    // Fluxos de Trabalho (isEditingTool: false)
    { id: 'aiPngCreator', name: 'Criador de PNG Transparente', description: 'Converta imagens para PNG com fundo transparente.', icon: React.createElement(PngIcon), category: 'workflow', isEditingTool: false },
    { id: 'photoStudio', name: 'Ensaio Fotográfico IA', description: 'Gere ensaios fotográficos realistas.', icon: React.createElement(CameraIcon), category: 'workflow', isEditingTool: false },
    { id: 'polaroid', name: 'Polaroid com Artista IA', description: 'Crie uma foto sua com seu artista favorito.', icon: React.createElement(PolaroidWithArtistIcon), category: 'workflow', isEditingTool: false },
    { id: 'superheroFusion', name: 'Fusão de Super-Herói', description: 'Transforme sua foto em um super-herói.', icon: React.createElement(SuperheroPoseIcon), category: 'workflow', isEditingTool: false },
    { id: 'styledPortrait', name: 'Retrato Estilizado', description: 'Aplique o estilo de uma foto em outra.', icon: React.createElement(StyledPortraitIcon), category: 'workflow', isEditingTool: false },
    { id: 'tryOn', name: 'Provador Virtual', description: 'Experimente roupas e calçados em uma foto.', icon: React.createElement(WardrobeIcon), category: 'workflow', isEditingTool: false },
    { id: 'interiorDesign', name: 'Reforma de Interiores', description: 'Visualize novos designs em suas fotos.', icon: React.createElement(HomeIcon), category: 'workflow', isEditingTool: false },
    { id: 'architecturalViz', name: 'Visualização Arquitetônica', description: 'Crie renderizações de alta qualidade.', icon: React.createElement(BuildingIcon), category: 'workflow', isEditingTool: false },
    { id: 'creativeFusion', name: 'Fusão Criativa', description: 'Combine composição com estilo.', icon: React.createElement(CombineIcon), category: 'workflow', isEditingTool: false },
    { id: 'doubleExposure', name: 'Dupla Exposição Artística', description: 'Combine um retrato e uma paisagem.', icon: React.createElement(DoubleExposureIcon), category: 'workflow', tag: 'new', isEditingTool: false },
    { id: 'outpainting', name: 'Pintura Expansiva', description: 'Amplie suas imagens expandindo o quadro.', icon: React.createElement(ExpandIcon), category: 'workflow', isEditingTool: false },
    { id: 'productPhotography', name: 'Fotografia de Produto AI', description: 'Gere fotos de produtos com qualidade de estúdio.', icon: React.createElement(SparkleIcon), category: 'workflow', isEditingTool: false },
    { id: 'aiPortraitStudio', name: 'Estúdio de Retrato IA', description: 'Transforme retratos com estilos criativos.', icon: React.createElement(CaricatureIcon), category: 'workflow', isEditingTool: false },
    { id: 'bananimate', name: 'Bananimate', description: 'Dê vida às suas fotos com animações.', icon: React.createElement(BananaIcon), category: 'workflow', isEditingTool: false },
    { id: 'confidentStudio', name: 'Retrato de Estúdio Confiante', description: 'Crie um retrato profissional e cinematográfico.', icon: React.createElement(UserIcon), category: 'workflow', isEditingTool: false },
    { id: 'funkoPopStudio', name: 'Estúdio Funko Pop', description: 'Transforme fotos em colecionáveis Funko Pop 3D.', icon: React.createElement(ToyIcon), category: 'workflow', isEditingTool: false },

    // Ferramentas de Edição (isEditingTool: true)
    { id: 'magicMontage', name: 'Montagem Mágica', description: 'Descreva qualquer edição e deixe a IA trabalhar.', icon: React.createElement(MagicWandIcon), category: 'editing', isEditingTool: true },
    { id: 'objectRemover', name: 'Removedor de Objetos', description: 'Pinte sobre objetos para removê-los.', icon: React.createElement(EraserIcon), category: 'editing', isEditingTool: true },
    { id: 'faceSwap', name: 'Troca de Rosto', description: 'Substitua o rosto em uma foto.', icon: React.createElement(SwapIcon), category: 'editing', isEditingTool: true },
    { id: 'generativeEdit', name: 'Edição Generativa', description: 'Selecione uma área para editar com texto.', icon: React.createElement(BrushIcon), category: 'editing', isEditingTool: true },
    { id: 'extractArt', name: 'Extrair Arte', description: 'Transforme sua foto em um esboço.', icon: React.createElement(LineArtIcon), category: 'editing', isEditingTool: true },
    { id: 'crop', name: 'Cortar e Girar', description: 'Ajuste o enquadramento e a orientação.', icon: React.createElement(CropIcon), category: 'editing', isEditingTool: true },
    { id: 'adjust', name: 'Ajustes Manuais', description: 'Controle fino de brilho, contraste, etc.', icon: React.createElement(AdjustmentsHorizontalIcon), category: 'editing', isEditingTool: true },
    { id: 'style', name: 'Estilo de Foto', description: "Aplique estilos artísticos como Anime, Van Gogh e mais à sua imagem.", icon: React.createElement(PaletteIcon), category: 'editing', isEditingTool: true },
    { id: 'unblur', name: 'Remover Desfoque', description: 'Corrija desfoques de movimento e lente.', icon: React.createElement(UnblurIcon), category: 'editing', isEditingTool: true },
    { id: 'sharpen', name: 'Nitidez Generativa', description: 'Realce contornos e texturas com IA.', icon: React.createElement(SharpenIcon), category: 'editing', isEditingTool: true },
    { id: 'text', name: 'Adicionar Texto', description: 'Adicione e estilize texto na imagem.', icon: React.createElement(TextToolIcon), category: 'editing', isEditingTool: true },
    { id: 'removeBg', name: 'Removedor de Fundo', description: 'Isole o objeto principal da imagem.', icon: React.createElement(ScissorsIcon), category: 'editing', isEditingTool: true },
    { id: 'upscale', name: 'Melhorar Resolução', description: 'Aumente a resolução sem perder qualidade.', icon: React.createElement(ArrowUpOnSquareIcon), category: 'editing', isEditingTool: true },
    { id: 'superResolution', name: 'Super Resolução IA', description: 'Aumente resolução e nitidez com um clique.', icon: React.createElement(SparkleIcon), category: 'editing', tag: 'new', isEditingTool: true },
    { id: 'photoRestoration', name: 'Restauração de Foto', description: 'Restaure fotos antigas removendo ruído.', icon: React.createElement(SparkleIcon), category: 'editing', isEditingTool: true },
    { id: 'relight', name: 'Reacender', description: 'Ajuste a iluminação com texto.', icon: React.createElement(LightbulbIcon), category: 'editing', isEditingTool: true },
    { id: 'lowPoly', name: 'Estilo Low Poly', description: 'Transforme em arte geométrica de polígonos.', icon: React.createElement(LowPolyIcon), category: 'editing', isEditingTool: true },
    { id: 'pixelArt', name: 'Pixel Art', description: 'Converta para o estilo clássico de pixel art.', icon: React.createElement(PixelsIcon), category: 'editing', isEditingTool: true },
    { id: 'portraits', name: 'Retratos IA', description: 'Ferramentas para melhorar retratos e avatares.', icon: React.createElement(UserIcon), category: 'editing', isEditingTool: true },
    { id: 'styleGen', name: 'Estilos Rápidos', description: 'Aplique estilos artísticos com um clique.', icon: React.createElement(BoltIcon), category: 'editing', isEditingTool: true },
    { id: 'dustAndScratches', name: 'Poeira e Arranhões', description: 'Adicione um efeito de filme antigo.', icon: React.createElement(FilmGrainIcon), category: 'editing', isEditingTool: true },
    { id: 'neuralFilters', name: 'Filtros Neurais', description: 'Aplique filtros criativos e atmosféricos.', icon: React.createElement(SparkleIcon), category: 'editing', isEditingTool: true },
    { id: 'trends', name: 'Tendências', description: 'Experimente estilos e efeitos populares.', icon: React.createElement(FireIcon), category: 'editing', isEditingTool: true },
    { id: 'vectorConverter', name: 'Conversor de Vetor', description: 'Converta imagens para arte vetorial.', icon: React.createElement(VectorIcon), category: 'editing', isEditingTool: true },
    { id: 'texture', name: 'Textura', description: 'Aplique sobreposições de textura.', icon: React.createElement(TextureIcon), category: 'editing', isEditingTool: true },
    { id: 'newAspectRatio', name: 'Proporção 16:9', description: 'Expanda sua imagem para a proporção 16:9.', icon: React.createElement(ExpandIcon), category: 'editing', isEditingTool: true },
];

export const toolToTabMap: Partial<Record<ToolId, TabId>> = {
    extractArt: 'extractArt',
    removeBg: 'removeBg',
    style: 'style',
    portraits: 'portraits',
    faceRecovery: 'photoRestoration',
    styleGen: 'styleGen',
    adjust: 'adjust',
    relight: 'relight',
    generativeEdit: 'generativeEdit',
    crop: 'crop',
    upscale: 'upscale',
    superResolution: 'superResolution',
    unblur: 'unblur',
    sharpen: 'sharpen',
    neuralFilters: 'neuralFilters',
    trends: 'trends',
    dustAndScratches: 'dustAndScratches',
    objectRemover: 'objectRemover',
    texture: 'texture',
    magicMontage: 'magicMontage',
    photoRestoration: 'photoRestoration',
    text: 'text',
    lowPoly: 'lowPoly',
    pixelArt: 'pixelArt',
    denoise: 'photoRestoration',
    faceSwap: 'faceSwap',
    localAdjust: 'localAdjust',
    newAspectRatio: 'newAspectRatio',
};