/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React from 'react';
import {
    BrushIcon, PhotoIcon, LayersIcon, SparkleIcon,
    FaceSmileIcon, VideoCameraIcon,
    AdjustmentsHorizontalIcon, CropIcon, PaletteIcon,
    ScissorsIcon, ArrowUpOnSquareIcon, TextToolIcon, LightbulbIcon,
    MagicWandIcon, LowPolyIcon, UserIcon, FilmGrainIcon, UnblurIcon,
    PatternIcon, TextEffectsIcon, VectorIcon, LogoIcon, StickersIcon, CaricatureIcon, Model3DIcon,
    BananaIcon,
    EraserIcon,
    ShirtIcon,
    CameraIcon,
    PolaroidIcon,
    TextureIcon,
    HomeIcon,
    BuildingIcon,
    CombineIcon,
    ExpandIcon,
    SwapIcon,
    LineArtIcon,
    FaceSparkleIcon,
    BoltIcon,
    FireIcon,
    PixelsIcon,
    ToyIcon,
    SharpenIcon,
} from '../components/icons';
import { type ToolId, type ToolConfig, type ToolCategory, type TabId } from '../types';

export const tools: ToolConfig[] = [
    // Generation Tools
    {
        id: 'imageGen',
        name: 'Gerador de Imagens AI',
        description: 'Crie imagens a partir de descrições de texto.',
        icon: React.createElement(PhotoIcon, { className: 'w-8 h-8 text-purple-400' }),
        category: 'generation',
    },
    {
        id: 'sketchRender',
        name: 'Renderização de Esboço',
        description: 'Transforme seus desenhos e esboços em imagens realistas com IA.',
        icon: React.createElement(BrushIcon, { className: 'w-8 h-8 text-blue-400' }),
        category: 'generation',
    },
    {
        id: 'characterDesign',
        name: 'Design de Personagem',
        description: 'Desenvolva conceitos de personagens para jogos, histórias e mais.',
        icon: React.createElement(FaceSmileIcon, { className: 'w-8 h-8 text-cyan-400' }),
        category: 'generation',
    },
    {
        id: 'videoGen',
        name: 'Gerador de Vídeo AI',
        description: 'Crie vídeos curtos e clipes animados a partir de texto.',
        icon: React.createElement(VideoCameraIcon, { className: 'w-8 h-8 text-red-400' }),
        category: 'generation',
    },
    {
        id: 'patternGen',
        name: 'Gerador de Padrões',
        description: 'Crie padrões de fundo sem costura para papéis de parede e designs.',
        icon: React.createElement(PatternIcon, { className: 'w-8 h-8 text-teal-400' }),
        category: 'generation',
    },
    {
        id: 'textEffects',
        name: 'Efeitos de Texto',
        description: 'Aplique efeitos visuais incríveis a um texto a partir de uma imagem.',
        icon: React.createElement(TextEffectsIcon, { className: 'w-8 h-8 text-amber-400' }),
        category: 'generation',
    },
    {
        id: 'logoGen',
        name: 'Gerador de Logotipo AI',
        description: 'Crie logotipos únicos e minimalistas a partir de um conceito.',
        icon: React.createElement(LogoIcon, { className: 'w-8 h-8 text-indigo-400' }),
        category: 'generation',
    },
    {
        id: 'stickerCreator',
        name: 'Criador de Adesivos AI',
        description: 'Gere adesivos em estilo de desenho animado a partir de um prompt.',
        icon: React.createElement(StickersIcon, { className: 'w-8 h-8 text-pink-400' }),
        category: 'generation',
    },
    {
        id: 'model3DGen',
        name: 'Gerador de Modelo 3D',
        description: 'Crie renderizações de objetos 3D a partir de uma descrição.',
        icon: React.createElement(Model3DIcon, { className: 'w-8 h-8 text-orange-400' }),
        category: 'generation',
    },


    // Workflows
    {
        id: 'photoStudio',
        name: 'Ensaio Fotográfico IA',
        description: 'Gere ensaios fotográficos realistas com cenários, roupas e iluminação personalizados.',
        icon: React.createElement(CameraIcon, { className: 'w-8 h-8 text-sky-400' }),
        category: 'workflow',
    },
    {
        id: 'polaroid',
        name: 'Polaroid com Artista IA',
        description: 'Crie uma foto Polaroid sua com seu artista favorito.',
        icon: React.createElement(PolaroidIcon, { className: 'w-8 h-8 text-stone-400' }),
        category: 'workflow',
    },
    {
        id: 'styledPortrait',
        name: 'Retrato Estilizado',
        description: 'Aplique o estilo (roupa, cenário, luz) de uma foto em outra, preservando o rosto original.',
        icon: React.createElement(ShirtIcon, { className: 'w-8 h-8 text-teal-400' }),
        category: 'workflow',
    },
     {
        id: 'tryOn',
        name: 'Provador Virtual',
        description: 'Experimente roupas e calçados em uma foto sua usando IA.',
        icon: React.createElement(ShirtIcon, { className: 'w-8 h-8 text-pink-400' }),
        category: 'workflow',
    },
    {
        id: 'interiorDesign',
        name: 'Reforma de Interiores',
        description: 'Visualize novos estilos de design em suas próprias fotos.',
        icon: React.createElement(HomeIcon, { className: 'w-8 h-8 text-teal-400' }),
        category: 'workflow',
    },
    {
        id: 'architecturalViz',
        name: 'Visualização Arquitetônica',
        description: 'Crie renderizações de alta qualidade para projetos arquitetônicos.',
        icon: React.createElement(BuildingIcon, { className: 'w-8 h-8 text-orange-400' }),
        category: 'workflow',
    },
    {
        id: 'creativeFusion',
        name: 'Fusão Criativa',
        description: 'Combine a composição de uma imagem com o estilo de outra.',
        icon: React.createElement(CombineIcon, { className: 'w-8 h-8 text-pink-400' }),
        category: 'workflow',
    },
    {
        id: 'outpainting',
        name: 'Pintura Expansiva',
        description: 'Amplie suas imagens expandindo o quadro em qualquer direção.',
        icon: React.createElement(ExpandIcon, { className: 'w-8 h-8 text-indigo-400' }),
        category: 'workflow',
    },
    {
        id: 'productPhotography',
        name: 'Fotografia de Produto AI',
        description: 'Gere fotos de produtos com qualidade de estúdio em qualquer cenário.',
        icon: React.createElement(SparkleIcon, { className: 'w-8 h-8 text-yellow-400' }),
        category: 'workflow',
    },
     {
        id: 'aiPortraitStudio',
        name: 'Estúdio de Retrato IA',
        description: 'Transforme retratos com estilos criativos como Caricatura, Pixar e mais.',
        icon: React.createElement(CaricatureIcon, { className: 'w-8 h-8 text-lime-400' }),
        category: 'workflow',
    },
    {
        id: 'bananimate',
        name: 'Bananimate',
        description: 'Dê vida às suas fotos com animações divertidas e personalizadas.',
        icon: React.createElement(BananaIcon, { className: 'w-8 h-8 text-yellow-400' }),
        category: 'workflow',
    },
    {
        id: 'confidentStudio',
        name: 'Retrato de Estúdio Confiante',
        description: 'Crie um retrato profissional em um estúdio com roupas elegantes e iluminação cinematográfica.',
        icon: React.createElement(UserIcon, { className: 'w-8 h-8 text-cyan-400' }),
        category: 'workflow',
    },
    {
        id: 'funkoPopStudio',
        name: 'Estúdio Funko Pop',
        description: 'Transforme fotos em colecionáveis Funko Pop 3D realistas com cenários personalizados.',
        icon: React.createElement(ToyIcon, { className: 'w-8 h-8 text-stone-400' }),
        category: 'workflow',
    },

    // Editing Tools
    {
        id: 'magicMontage',
        name: 'Montagem Mágica',
        description: 'Descreva qualquer edição e deixe a IA transformar sua foto como um profissional.',
        icon: React.createElement(MagicWandIcon, { className: 'w-8 h-8 text-purple-400' }),
        category: 'editing',
    },
     {
        id: 'objectRemover',
        name: 'Removedor de Objetos',
        description: 'Pinte sobre objetos indesejados para removê-los magicamente.',
        icon: React.createElement(EraserIcon, { className: 'w-8 h-8 text-red-400' }),
        category: 'editing',
    },
    {
        id: 'faceSwap',
        name: 'Troca de Rosto',
        description: 'Substitua o rosto em uma foto pelo de outra de forma realista.',
        icon: React.createElement(SwapIcon, { className: 'w-8 h-8 text-red-400' }),
        category: 'editing',
    },
    {
        id: 'generativeEdit',
        name: 'Edição Generativa',
        description: 'Selecione uma área para remover, adicionar ou alterar objetos com texto.',
        icon: React.createElement(BrushIcon, { className: 'w-8 h-8 text-fuchsia-400' }),
        category: 'editing',
    },
    {
        id: 'extractArt',
        name: 'Extrair Arte',
        description: 'Transforme sua foto em um esboço de linhas e contornos.',
        icon: React.createElement(LineArtIcon, { className: 'w-8 h-8 text-gray-400' }),
        category: 'editing',
    },
    {
        id: 'crop',
        name: 'Cortar e Girar',
        description: 'Ajuste o enquadramento, a proporção e a orientação da sua imagem.',
        icon: React.createElement(CropIcon, { className: 'w-8 h-8 text-lime-400' }),
        category: 'editing',
    },
    {
        id: 'adjust',
        name: 'Ajustes Manuais',
        description: 'Controle fino de brilho, contraste, saturação e outras propriedades.',
        icon: React.createElement(AdjustmentsHorizontalIcon, { className: 'w-8 h-8 text-gray-400' }),
        category: 'editing',
    },
    {
        id: 'style',
        name: 'Estilos Artísticos',
        description: 'Transforme sua foto com estilos de arte famosos usando IA.',
        icon: React.createElement(PaletteIcon, { className: 'w-8 h-8 text-amber-400' }),
        category: 'editing',
    },
     {
        id: 'unblur',
        name: 'Remover Desfoque',
        description: 'Corrija desfoque de movimento e lente com IA para aguçar sua imagem.',
        icon: React.createElement(UnblurIcon, { className: 'w-8 h-8 text-cyan-400' }),
        category: 'editing',
    },
    {
        id: 'sharpen',
        name: 'Nitidez Generativa',
        description: 'Realce contornos e texturas com nitidez inteligente de IA.',
        icon: React.createElement(SharpenIcon, { className: 'w-8 h-8 text-cyan-400' }),
        category: 'editing',
    },
    {
        id: 'text',
        name: 'Adicionar Texto',
        description: 'Adicione e estilize texto diretamente na sua imagem.',
        icon: React.createElement(TextToolIcon, { className: 'w-8 h-8 text-orange-400' }),
        category: 'editing',
    },
    {
        id: 'removeBg',
        name: 'Removedor de Fundo',
        description: 'Isole o objeto principal da sua imagem com um clique.',
        icon: React.createElement(ScissorsIcon, { className: 'w-8 h-8 text-sky-400' }),
        category: 'editing',
    },
    {
        id: 'upscale',
        name: 'Melhorar Resolução',
        description: 'Aumente a resolução e a nitidez da imagem sem perder qualidade.',
        icon: React.createElement(ArrowUpOnSquareIcon, { className: 'w-8 h-8 text-emerald-400' }),
        category: 'editing',
    },
    {
        id: 'photoRestoration',
        name: 'Restauração de Foto',
        description: 'Restaure fotos antigas removendo ruído, arranhões e melhorando rostos.',
        icon: React.createElement(SparkleIcon, { className: 'w-8 h-8 text-yellow-300' }),
        category: 'editing',
    },
    {
        id: 'relight',
        name: 'Reacender',
        description: 'Ajuste a iluminação da sua foto com descrições de texto.',
        icon: React.createElement(LightbulbIcon, { className: 'w-8 h-8 text-yellow-400' }),
        category: 'editing',
    },
    {
        id: 'lowPoly',
        name: 'Estilo Low Poly',
        description: 'Transforme sua foto em uma arte geométrica de polígonos.',
        icon: React.createElement(LowPolyIcon, { className: 'w-8 h-8 text-cyan-400' }),
        category: 'editing',
    },
    {
        id: 'pixelArt',
        name: 'Pixel Art',
        description: 'Converta sua imagem para o estilo clássico de pixel art.',
        icon: React.createElement(PixelsIcon, { className: 'w-8 h-8 text-green-400' }),
        category: 'editing',
    },
    {
        id: 'portraits',
        name: 'Retratos IA',
        description: 'Ferramentas com um clique para melhorar retratos e avatares.',
        icon: React.createElement(UserIcon, { className: 'w-8 h-8 text-rose-400' }),
        category: 'editing',
    },
    {
        id: 'styleGen',
        name: 'Estilos Rápidos',
        description: 'Aplique estilos artísticos predefinidos com um clique.',
        icon: React.createElement(BoltIcon, { className: 'w-8 h-8 text-teal-400' }),
        category: 'editing',
    },
    {
        id: 'dustAndScratches',
        name: 'Poeira e Arranhões',
        description: 'Adicione um efeito de filme antigo com poeira e arranhões.',
        icon: React.createElement(FilmGrainIcon, { className: 'w-8 h-8 text-stone-400' }),
        category: 'editing',
    },
     {
        id: 'neuralFilters',
        name: 'Filtros Neurais',
        description: 'Aplique filtros criativos e atmosféricos com um clique.',
        icon: React.createElement(SparkleIcon, { className: 'w-8 h-8 text-indigo-400' }),
        category: 'editing',
    },
    {
        id: 'trends',
        name: 'Tendências',
        description: 'Experimente estilos e efeitos populares do momento.',
        icon: React.createElement(FireIcon, { className: 'w-8 h-8 text-pink-400' }),
        category: 'editing',
    },
    {
        id: 'vectorConverter',
        name: 'Conversor de Vetor',
        description: 'Converta imagens bitmap para um estilo de arte vetorial.',
        icon: React.createElement(VectorIcon, { className: 'w-8 h-8 text-orange-400' }),
        category: 'editing',
    },
    {
        id: 'texture',
        name: 'Textura',
        description: 'Aplique sobreposições de textura como grão de filme, papel e mais.',
        icon: React.createElement(TextureIcon, { className: 'w-8 h-8 text-lime-400' }),
        category: 'editing',
    },
    {
        id: 'newAspectRatio',
        name: 'Proporção 16:9',
        description: 'Expanda sua imagem para a proporção de paisagem (16:9) usando IA.',
        icon: React.createElement(ExpandIcon, { className: 'w-8 h-8 text-indigo-400' }),
        category: 'editing',
    },
];


export const toolToTabMap: Partial<Record<ToolId, TabId>> = {
    extractArt: 'extractArt',
    removeBg: 'removeBg',
    style: 'style',
    portraits: 'portraits',
    faceRecovery: 'photoRestoration',
    styleGen: 'styleGen',
    adjust: 'adjust',
    relight: 'relight',
    generativeEdit: 'generativeEdit',
    crop: 'crop',
    upscale: 'upscale',
    unblur: 'unblur',
    sharpen: 'sharpen',
    neuralFilters: 'neuralFilters',
    trends: 'trends',
    dustAndScratches: 'dustAndScratches',
    objectRemover: 'objectRemover',
    texture: 'texture',
    magicMontage: 'magicMontage',
    photoRestoration: 'photoRestoration',
    text: 'text',
    lowPoly: 'lowPoly',
    pixelArt: 'pixelArt',
    denoise: 'photoRestoration',
    faceSwap: 'faceSwap',
    localAdjust: 'localAdjust',
    newAspectRatio: 'newAspectRatio',
};